defaults: &defaults
  host: localhost
  port: 27017
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  <<: *defaults
  database: bchagas_dev

test:
  <<: *defaults
  database: bchagas_test

production:
  uri: <%= ENV['MONGOHQ_URL'] %>
